// Export pages
export '/others/b_a_s_e_global_wallet_dashboard/b_a_s_e_global_wallet_dashboard_widget.dart'
    show BASEGlobalWalletDashboardWidget;
export '/o_l_d_gestion_wallet/g_e_s_t_i_o_n_w_a_l_l_e_t_add_transaction/g_e_s_t_i_o_n_w_a_l_l_e_t_add_transaction_widget.dart'
    show GESTIONWALLETAddTransactionWidget;
export '/o_l_d_gestion_wallet/g_e_s_t_i_o_n_w_a_l_l_e_t_transaction_history/g_e_s_t_i_o_n_w_a_l_l_e_t_transaction_history_widget.dart'
    show GESTIONWALLETTransactionHistoryWidget;
export '/o_l_d_gestion_budget/b_a_s_e_budget_management/b_a_s_e_budget_management_widget.dart'
    show BASEBudgetManagementWidget;
export '/o_l_d_gestion_budget/g_e_s_t_i_o_n_b_u_d_g_e_t_budget_details/g_e_s_t_i_o_n_b_u_d_g_e_t_budget_details_widget.dart'
    show GESTIONBUDGETBudgetDetailsWidget;
export '/o_l_d_gestion_budget/g_e_s_t_i_o_n_b_u_d_g_e_t_set_new_budget/g_e_s_t_i_o_n_b_u_d_g_e_t_set_new_budget_widget.dart'
    show GESTIONBUDGETSetNewBudgetWidget;
export '/o_l_d_gestion_group/b_a_s_e_split_expenses_groups/b_a_s_e_split_expenses_groups_widget.dart'
    show BASESplitExpensesGroupsWidget;
export '/o_l_d_gestion_group/g_e_s_t_i_o_n_g_r_o_u_p_e_s_create_group/g_e_s_t_i_o_n_g_r_o_u_p_e_s_create_group_widget.dart'
    show GESTIONGROUPESCreateGroupWidget;
export '/o_l_d_gestion_group/g_e_s_t_i_o_n_g_r_o_u_p_e_s_add_expense/g_e_s_t_i_o_n_g_r_o_u_p_e_s_add_expense_widget.dart'
    show GESTIONGROUPESAddExpenseWidget;
export '/o_l_d_gestion_group/g_e_s_t_i_o_n_g_r_o_u_p_e_s_group_details/g_e_s_t_i_o_n_g_r_o_u_p_e_s_group_details_widget.dart'
    show GESTIONGROUPESGroupDetailsWidget;
export '/o_l_d_gestion_invest/b_a_s_e_investments_savings_goals/b_a_s_e_investments_savings_goals_widget.dart'
    show BASEInvestmentsSavingsGoalsWidget;
export '/o_l_d_gestion_invest/g_e_s_t_i_o_n_i_n_v_e_s_t_goal_details/g_e_s_t_i_o_n_i_n_v_e_s_t_goal_details_widget.dart'
    show GESTIONINVESTGoalDetailsWidget;
export '/o_l_d_gestion_invest/g_e_s_t_i_o_n_i_n_v_e_s_t_set_new_goal/g_e_s_t_i_o_n_i_n_v_e_s_t_set_new_goal_widget.dart'
    show GESTIONINVESTSetNewGoalWidget;
export '/others/profile_security/profile_security_widget.dart'
    show ProfileSecurityWidget;
export '/others/transaction_history/transaction_history_widget.dart'
    show TransactionHistoryWidget;
export '/authentication/a_u_t_h_login/a_u_t_h_login_widget.dart'
    show AUTHLoginWidget;
export '/authentication/a_u_t_h_register/a_u_t_h_register_widget.dart'
    show AUTHRegisterWidget;
export '/authentication/a_u_t_h_forgot_password/a_u_t_h_forgot_password_widget.dart'
    show AUTHForgotPasswordWidget;
export '/authentication/a_u_t_h_profile_setup/a_u_t_h_profile_setup_widget.dart'
    show AUTHProfileSetupWidget;
export '/authentication/a_u_t_h_onboarding/a_u_t_h_onboarding_widget.dart'
    show AUTHOnboardingWidget;
export '/authentication/b_a_s_e_notifications_center/b_a_s_e_notifications_center_widget.dart'
    show BASENotificationsCenterWidget;
export '/authentication/b_a_s_e_general_settings/b_a_s_e_general_settings_widget.dart'
    show BASEGeneralSettingsWidget;
export '/gestion_cartes/the_main_mes_cartes_dashboard_view_cards_transactions/the_main_mes_cartes_dashboard_view_cards_transactions_widget.dart'
    show TheMainMesCartesDashboardViewCardsTransactionsWidget;
export '/gestion_cartes/ajouterune_carte_form_createa_new_card/ajouterune_carte_form_createa_new_card_widget.dart'
    show AjouteruneCarteFormCreateaNewCardWidget;
export '/gestion_cartes/paramtresdela_carte_update_card_limits_status/paramtresdela_carte_update_card_limits_status_widget.dart'
    show ParamtresdelaCarteUpdateCardLimitsStatusWidget;
export '/aa/aa_widget.dart' show AaWidget;
export '/authentication/a_u_t_h_onboarding2/a_u_t_h_onboarding2_widget.dart'
    show AUTHOnboarding2Widget;
export '/gestion_cartes/recharger_carte/recharger_carte_widget.dart'
    show RechargerCarteWidget;
export '/gestion_cartes/ajouterune_transaction/ajouterune_transaction_widget.dart'
    show AjouteruneTransactionWidget;
export '/gestion_cartes/analytiques_transactions/analytiques_transactions_widget.dart'
    show AnalytiquesTransactionsWidget;
export '/gestion_wallet/add_wallet/add_wallet_widget.dart' show AddWalletWidget;
export '/gestion_wallet/wallet_dashboard/wallet_dashboard_widget.dart'
    show WalletDashboardWidget;
export '/gestion_wallet/wallet_list/wallet_list_widget.dart'
    show WalletListWidget;
export '/gestion_wallet/show_revenu/show_revenu_widget.dart'
    show ShowRevenuWidget;
export '/gestion_wallet/add_revenu/add_revenu_widget.dart' show AddRevenuWidget;
export '/gestion_wallet/edit_revenu/edit_revenu_widget.dart'
    show EditRevenuWidget;
export '/gestion_wallet/edit_wallet/edit_wallet_widget.dart'
    show EditWalletWidget;
export '/gestion_invest/dashboardinvestments/dashboardinvestments_widget.dart'
    show DashboardinvestmentsWidget;
export '/gestion_invest/bitcoin_page/bitcoin_page_widget.dart'
    show BitcoinPageWidget;
export '/gestion_invest/smart_recommendation_page/smart_recommendation_page_widget.dart'
    show SmartRecommendationPageWidget;
export '/gestion_invest/invdetails/invdetails_widget.dart'
    show InvdetailsWidget;
